### ISSUE TITLE
Integration works intermittently

### ISSUE THREAD

**Issue by etho201** [sebirdman/deako_hass_integration#6]
## Version of the custom_component

0.0.1

## Describe the bug

This integration is very unreliable. It sometimes works, but most of the time I am unable to control my Deako lights using Home Assistant. When I check the logs, it looks to fail due to a global task timeout (see logs below).

## Debug log

```text

Error setting up entry 192.168.1.101 for deako
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deako/__init__.py", line 41, in async_setup_entry
    await connection.connect()
  File "/config/custom_components/deako/deako.py", line 204, in connect
    await self.connection.wait_for_connect()
  File "/config/custom_components/deako/deako.py", line 87, in wait_for_connect
    await asyncio.sleep(1)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 649, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Global task timeout

```

I also see a "failed to connect" message:

```

This error originated from a custom integration.

Logger: custom_components.deako
Source: custom_components/deako/deako.py:96
Integration: Deako Smart Lighting (documentation, issues)
First occurred: 1:20:52 AM (42 occurrences)
Last logged: 1:44:42 AM

Failed to connect

```

**Comment by etho201** [comment]
Here's another message I'm seeing in the logs:

```

This error originated from a custom integration.

Logger: custom_components.deako
Source: custom_components/deako/deako.py:59
Integration: Deako Smart Lighting (documentation, issues)
First occurred: 1:50:47 AM (17 occurrences)
Last logged: 1:55:08 AM

Got partial message

```

```
2024-01-22 02:00:26.609 ERROR (Thread-20) [custom_components.deako] Failed to connect
2024-01-22 02:01:10.272 ERROR (Thread-2) [custom_components.deako] Got partial message
2024-01-22 02:01:10.274 ERROR (Thread-2) [custom_components.deako] Got partial message
2024-01-22 02:01:10.777 ERROR (Thread-21) [custom_components.deako] Got partial message
2024-01-22 02:01:10.780 ERROR (Thread-21) [custom_components.deako] Got partial message
2024-01-22 02:02:41.435 ERROR (Thread-20) [custom_components.deako] Failed to connect

```
